---
kind: pipeline
type: docker
name: test
steps:
- name: install
  image: danlynn/ember-cli:3.20.0
  commands:
  - npm ci
- name: lint:js
  image: danlynn/ember-cli:3.20.0
  commands:
  - npm run lint:js
- name: lint:hbs
  image: danlynn/ember-cli:3.20.0
  commands:
  - npm run lint:hbs
- name: lint:dependencies
  image: danlynn/ember-cli:3.20.0
  failure: ignore
  commands:
  - ember dependency-lint
- name: test
  image: danlynn/ember-cli:3.20.0
  failure: ignore
  commands:
  - npm run test:ember
---
kind: pipeline
type: docker
name: release
steps:
- name: npm-release
  image: plugins/npm
  settings:
    token:
      from_secret: npm_access_token
trigger:
  event:
    - tag
---
kind: secret
name: npm_access_token
data: QQWCpJTEvR8mACOHTpfDdwHwWXmmihRL/KCLLC8KBfyma2u/w03o0UuK8E7lQn3BKtNgpvrbeor8bTGbWFfI1fIhzJM=
---
kind: signature
hmac: 382333a475daa4a26b3cab2315b46d2cdf5bfa0bdfbc292dc9eedfe209ddbe65

...
